"""Source-to-source backend: emit a runnable Python script equivalent to
running the in-memory behaviour tree under the osc2carla CLI.

Walks the annotated AST and pretty-prints a standalone .py file that
recreates the same py_trees tree using the same atomic_behaviors classes
and ExecutionContext.  The emitted script is what a user might write by
hand instead of invoking ``python -m osc2carla``.
"""
from __future__ import annotations

from io import StringIO
from typing import List, Optional

from ..frontend import nodes
from ..middle import AnnotatedScenario


_HEADER = '''"""Auto-generated by osc2carla codegen from {source}.

Equivalent hand-written runtime for the scenario.  Run with:
    python {{this_file}} --record-video out.mp4
"""
from __future__ import annotations

import argparse
import sys
import time

import py_trees

from osc2carla.middle import analyse
from osc2carla.backend import (
    BehaviorTreeBuilder, ExecutionContext, Recorder, ScenarioInitializer,
)
from osc2carla.backend.atomic_behaviors import (
    AssignCelestial, ChangeTargetSpeed, LaneChangeLite, RamTarget, SetLights,
    WaypointFollowerLite, _Noop,
)
from osc2carla.backend.behavior_tree import _ConditionLeaf, _EmitLeaf
from osc2carla.backend.context import _ActorHandle, Quantity


SCENARIO_SOURCE = {source!r}


def build_tree(ctx):
'''


def emit(annotated: AnnotatedScenario, source_path: str) -> str:
    out = StringIO()
    out.write(_HEADER.format(source=source_path))

    scenario = annotated.scenario

    out.write("    # ---- actor handles (bound at runtime by ScenarioInitializer) ----\n")
    for b in scenario.actors:
        if b.type_name in ("vehicle", "stationary_object"):
            out.write(f"    {b.name} = _ActorHandle(ctx, {b.name!r})\n")
    out.write("\n")

    if scenario.variables:
        out.write("    # ---- scenario variables ----\n")
        for v in scenario.variables:
            init = ctx_value_repr(v) if v.initializer is None else _expr_repr(v.initializer)
            out.write(f"    ctx._vars[{v.name!r}] = {init}\n")
        out.write("\n")

    out.write("    # ---- behaviour tree ----\n")
    if scenario.do is None:
        out.write("    return py_trees.behaviours.Success(name='Empty')\n")
    else:
        expr = _emit_member(scenario.do.body, indent=1)
        out.write(f"    root = {expr}\n")
        out.write("    return root\n")

    out.write(_FOOTER)
    return out.getvalue()


_FOOTER = '''

#: Actor categories no CARLA map ships, and which therefore can only be left
#: over from a previous run on this world.
LEFTOVER_PREFIXES = ("vehicle.", "walker.", "sensor.", "static.prop.")


def _clear_leftover_actors(world) -> int:
    """Destroy actors a previous run left in this world. Returns the count."""
    try:
        actors = list(world.get_actors())
    except (RuntimeError, AttributeError):
        return 0
    doomed = [a for a in actors
              if str(getattr(a, "type_id", "")).startswith(LEFTOVER_PREFIXES)]
    if not doomed:
        return 0
    # Sensors first: a sensor outlives its parent's destruction and keeps
    # streaming into a callback that no longer has anywhere to put the data.
    doomed.sort(key=lambda a: not str(a.type_id).startswith("sensor."))
    cleared = 0
    for actor in doomed:
        try:
            if str(actor.type_id).startswith("sensor."):
                try:
                    actor.stop()
                except (RuntimeError, AttributeError):
                    pass
            actor.destroy()
            cleared += 1
        except RuntimeError:
            pass          # already gone, which is the outcome we wanted
    try:
        world.tick()
    except RuntimeError:
        pass
    print("[codegen] cleared %d actor(s) left over from a previous run on this "
          "world" % cleared)
    return cleared


def main(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=2000)
    p.add_argument("--carla-timeout", type=float, default=240.0)
    p.add_argument("--timeout", type=float, default=30.0)
    p.add_argument("--fixed-dt", type=float, default=0.05)
    p.add_argument("--record-video", default=None)
    p.add_argument("--record-actor", default=None)
    p.add_argument("--record-width", type=int, default=1280)
    p.add_argument("--record-height", type=int, default=720)
    p.add_argument("--record-fps", type=int, default=20)
    args = p.parse_args(argv)

    annotated = analyse(SCENARIO_SOURCE)

    import carla  # type: ignore
    client = carla.Client(args.host, args.port)
    client.set_timeout(args.carla_timeout)
    world = client.get_world()
    map_attr = next((b for b in annotated.scenario.actors if b.type_name == "map"), None)
    map_name = (getattr(map_attr, "attributes", {}) or {}).get("map_file", "Town10HD_Opt")
    cur_map = world.get_map().name
    if not (cur_map.endswith(map_name) or map_name.endswith(cur_map.split("/")[-1])):
        world = client.load_world(map_name)
    else:
        # Same town as whatever ran last, so load_world is skipped -- and with it
        # the actor cleanup a map change gives for free. A run that died between
        # spawning and teardown therefore leaves its whole cast standing, and the
        # next run spawns a second cast on top of it: the ego ends up overlapping
        # a copy of itself, pinned by physics, reporting a collision on every
        # tick against an actor whose role_name is also 'ego'. That is a silently
        # wrong result, not a crash, which is the dangerous kind. Nothing a map
        # ships is a vehicle, a walker, a sensor or a spawned prop, so clearing
        # those is safe and is what a map change would have done anyway.
        _clear_leftover_actors(world)
    carla_map = world.get_map()

    settings = world.get_settings()
    original = world.get_settings()
    settings.synchronous_mode = True
    settings.fixed_delta_seconds = args.fixed_dt
    world.apply_settings(settings)

    ctx = ExecutionContext(annotated, world=world, carla_map=carla_map)
    init = ScenarioInitializer(world, carla_map, annotated, ctx)
    init.initialise()
    world.tick()

    recorder = None
    if args.record_video:
        rec_binding = args.record_actor
        if rec_binding is None:
            for b in annotated.scenario.actors:
                if b.type_name == "vehicle":
                    rec_binding = b.name
                    break
        rec_actor = ctx.actor(rec_binding) if rec_binding else None
        if rec_actor is not None:
            recorder = Recorder(world, rec_actor, args.record_video,
                                width=args.record_width,
                                height=args.record_height,
                                fps=args.record_fps)

    root = build_tree(ctx)
    tree = py_trees.trees.BehaviourTree(root=root)
    tree.setup(timeout=15)
    ctx.blackboard["go_signal"] = True

    t0 = time.time(); sim_t = 0.0
    try:
        while time.time() - t0 < args.timeout:
            world.tick(); sim_t += args.fixed_dt
            ctx.advance_tick(sim_t)
            tree.tick()
            if recorder is not None:
                recorder.tick(sim_t)
            if tree.root.status in (py_trees.common.Status.SUCCESS,
                                     py_trees.common.Status.FAILURE):
                break
    finally:
        if recorder is not None:
            recorder.finalize()
        world.apply_settings(original)
        for a in list(getattr(init, "_spawned", [])):
            try: a.destroy()
            except Exception: pass


if __name__ == "__main__":
    sys.exit(main())
'''


def _emit_member(member, indent: int) -> str:
    pad = "    " * indent
    if isinstance(member, nodes.Composition):
        if member.op == "serial":
            head = "py_trees.composites.Sequence(name='serial', memory=True)"
        elif member.op == "parallel":
            head = ("py_trees.composites.Parallel(name='parallel', "
                    "policy=py_trees.common.ParallelPolicy.SuccessOnAll(synchronise=False))")
        elif member.op == "one_of":
            head = ("py_trees.composites.Parallel(name='one_of', "
                    "policy=py_trees.common.ParallelPolicy.SuccessOnOne())")
        else:
            head = f"py_trees.composites.Sequence(name={member.op!r}, memory=True)"
        kids = ",\n".join(pad + "    " + _emit_member(c, indent + 1) for c in member.members)
        return f"_composite({head}, [\n{kids}\n{pad}])"
    if isinstance(member, nodes.ActionCall):
        return _emit_action_call(member)
    if isinstance(member, nodes.Wait):
        return f"_ConditionLeaf({_expr_repr(member.condition)}, ctx, name='Wait[{_summary(member.condition)}]')"
    if isinstance(member, nodes.Emit):
        return f"_EmitLeaf({member.event!r}, ctx)"
    return "py_trees.behaviours.Success(name='Noop')"


def _speed_modifier_repr(mods) -> Optional[str]:
    """Source for a ``speed(...)`` modifier's setpoint, or None if absent."""
    for m in mods:
        if m.name != "speed":
            continue
        if m.args.positional:
            return _expr_repr(m.args.positional[0])
        if "target" in m.args.named:
            return _expr_repr(m.args.named["target"])
    return None


def _emit_action_call(action: nodes.ActionCall) -> str:
    """Emit a direct constructor call for the atomic behaviour, mirroring
    the dispatch logic in atomic_behaviors.py."""
    actor = action.actor or "None"
    name = action.behaviour
    mods = action.with_block.modifiers if action.with_block else []
    args = action.args

    if name in ("ram",):
        target = _expr_repr(args.named["target"]) if "target" in args.named else "None"
        return f"RamTarget({actor}, {target}, ctx, name='Ram[{actor}->{_arg_name(args.named.get('target'))}]')"
    if name in ("drive",):
        v = _speed_modifier_repr(mods) or "0.0"
        keep_lane = any(m.name == "keep_lane" for m in mods)
        return (f"WaypointFollowerLite({actor}, {v}, ctx, "
                f"name='Drive[{actor}]', keep_lane={keep_lane!r})")
    if name in ("change_speed",):
        tgt = _expr_repr(args.named.get("target", nodes.NumLit(0.0)))
        prof = "smooth"
        if "rate_profile" in args.named:
            r = args.named["rate_profile"]
            if isinstance(r, nodes.Identifier) and r.name == "asap":
                prof = "asap"
        return (f"ChangeTargetSpeed({actor}, {tgt}, ctx, profile={prof!r}, "
                f"name='ChangeSpeed[{actor}]')")
    if name in ("change_lane",):
        n = _expr_repr(args.named.get("num_of_lanes", nodes.NumLit(1, True)))
        # `side: left` is an enum member, not a variable: emitting it as a bare
        # name would be a NameError in the generated script.
        side_expr = args.named.get("side", nodes.Identifier("right"))
        side = repr(side_expr.name) if isinstance(side_expr, nodes.Identifier) \
            else _expr_repr(side_expr)
        v = _speed_modifier_repr(mods)
        return (f"LaneChangeLite({actor}, int({n}), str({side}), ctx, "
                f"v_setpoint={v or 'None'}, name='LaneChange[{actor}]')")
    if name in ("set_lights",):
        mode = _expr_repr(args.named.get("mode", nodes.StringLit("auto")))
        return f"SetLights({actor}, str({mode}), name='SetLights[{actor}]')"
    if name in ("assign_position",):
        return f"_Noop(name='AssignPosition[{actor}]')"
    if name in ("assign_celestial_position",):
        az = _expr_repr(args.named["azimuth"])
        el = _expr_repr(args.named["elevation"])
        return (f"AssignCelestial(ctx, _deg({az}), _deg({el}))")
    return f"py_trees.behaviours.Success(name='Unmapped[{name}]')"


def _expr_repr(expr) -> str:
    if isinstance(expr, nodes.NumLit):
        return repr(int(expr.value) if expr.is_int else expr.value)
    if isinstance(expr, nodes.BoolLit):
        return repr(expr.value)
    if isinstance(expr, nodes.StringLit):
        return repr(expr.value)
    if isinstance(expr, nodes.PhysicalLiteral):
        return f"Quantity._from_unit({expr.value!r}, {expr.unit!r}, ctx)"
    if isinstance(expr, nodes.Identifier):
        return expr.name
    if isinstance(expr, nodes.QualifiedIdentifier):
        return expr.name
    if isinstance(expr, nodes.BinaryExpr):
        return f"({_expr_repr(expr.left)} {expr.op} {_expr_repr(expr.right)})"
    if isinstance(expr, nodes.UnaryExpr):
        return f"(- {_expr_repr(expr.operand)})" if expr.op == "-" else f"(not {_expr_repr(expr.operand)})"
    if isinstance(expr, nodes.MemberAccess):
        return f"{_expr_repr(expr.target)}.{expr.field}"
    if isinstance(expr, nodes.Elapsed):
        return f"_elapsed(ctx, {_expr_repr(expr.duration)})"
    if isinstance(expr, nodes.Rise):
        return f"_rise(ctx, lambda: {_expr_repr(expr.expr)})"
    if isinstance(expr, nodes.Fall):
        return f"_fall(ctx, lambda: {_expr_repr(expr.expr)})"
    if isinstance(expr, nodes.EventRef):
        return f"ctx.blackboard.get({expr.name!r}, False)"
    return repr(expr)


def _summary(expr) -> str:
    if isinstance(expr, nodes.Elapsed):
        return "elapsed"
    if isinstance(expr, nodes.Rise):
        return "rise"
    if isinstance(expr, nodes.Fall):
        return "fall"
    if isinstance(expr, nodes.EventRef):
        return "@" + expr.name
    return type(expr).__name__


def _arg_name(expr) -> str:
    if isinstance(expr, nodes.Identifier):
        return expr.name
    return "?"


def ctx_value_repr(v) -> str:
    return "0.0"
